#encoding: utf-8

development:
  adapter: postgresql
  encoding: unicode
  database: dev_loventine
  username: edgardo
  password: 12345
  host: localhost
  port: 5432

test:
  adapter: postgresql
  encoding: unicode
  database: test_loventine
  username: edgardo
  password: 12345
  host: localhost
  port: 5432
